import React, { useState } from 'react';
import { AnomalyAlert, TabView, UserRole } from '../types/sense';
import {
  ShieldCheck,
  CheckCircle2,
  Droplets,
  Zap,
  Layers,
  Eye,
  Wind,
  Users,
} from 'lucide-react';

interface AlertsCenterProps {
  userRole: UserRole;
  alerts: AnomalyAlert[];
  onResolveAlert: (id: string) => void;
  setCurrentTab: (tab: TabView) => void;
  setSelectedFloorForTwin: (floor: number) => void;
}

export const AlertsCenter: React.FC<AlertsCenterProps> = ({
  userRole,
  alerts,
  onResolveAlert,
  setCurrentTab,
  setSelectedFloorForTwin,
}) => {
  const isUser = userRole === 'user';
  // Only owner and administrator can resolve/fix anomalies
  const canResolve = userRole === 'owner' || userRole === 'administrator';
  // Only owner and administrator can simulate in Twin
  const canSimulate = userRole === 'owner' || userRole === 'administrator';

  const [filter, setFilter] = useState<'all' | 'unresolved' | 'water' | 'energy'>('all');

  // All roles now see all building alerts (no floor-4 restriction for users)
  const filteredAlerts = alerts.filter((a) => {
    if (filter === 'unresolved') return !a.resolved;
    if (filter === 'water') return a.category === 'water';
    if (filter === 'energy') return a.category === 'energy';
    return true;
  });

  const handleSimulateInTwin = (floor: number) => {
    setSelectedFloorForTwin(floor);
    setCurrentTab('digital_twin');
  };

  const getCategoryIcon = (category: AnomalyAlert['category']) => {
    switch (category) {
      case 'water': return <Droplets size={22} />;
      case 'air': return <Wind size={22} />;
      case 'occupancy': return <Users size={22} />;
      default: return <Zap size={22} />;
    }
  };

  return (
    <div>
      {/* Title & Filters */}
      <div style={{ marginBottom: 24, display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12 }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <h2 style={{ fontSize: 24, fontWeight: 700 }}>Edge Anomaly Detection & Incident Center</h2>
            {isUser && (
              <span
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: 5,
                  background: 'rgba(56, 189, 248, 0.12)',
                  border: '1px solid rgba(56, 189, 248, 0.3)',
                  color: 'var(--accent-cyan)',
                  borderRadius: 'var(--radius-pill)',
                  fontSize: 10,
                  fontWeight: 700,
                  padding: '3px 10px',
                  fontFamily: 'var(--font-mono)',
                  textTransform: 'uppercase',
                  letterSpacing: '0.05em',
                }}
              >
                <Eye size={11} />
                View Only
              </span>
            )}
          </div>
          <p style={{ color: 'var(--text-secondary)', fontSize: 13, marginTop: 4 }}>
            Zero-latency edge flags generated by offline-first heuristics and machine learning baselines.
            {isUser && <span style={{ color: 'var(--accent-cyan)', marginLeft: 6 }}>Alert states update live as your building owner acts on them.</span>}
          </p>
        </div>

        {/* Filter Pills */}
        <div style={{ display: 'flex', gap: 6, background: 'rgba(0,0,0,0.3)', padding: 4, borderRadius: 'var(--radius-pill)' }}>
          <button
            id="filter-all"
            className={`panel-btn ${filter === 'all' ? 'active' : ''}`}
            onClick={() => setFilter('all')}
          >
            All ({alerts.length})
          </button>
          <button
            id="filter-unresolved"
            className={`panel-btn ${filter === 'unresolved' ? 'active' : ''}`}
            onClick={() => setFilter('unresolved')}
          >
            Active ({alerts.filter((a) => !a.resolved).length})
          </button>
          <button
            id="filter-water"
            className={`panel-btn ${filter === 'water' ? 'active' : ''}`}
            onClick={() => setFilter('water')}
          >
            Water Leaks
          </button>
          <button
            id="filter-energy"
            className={`panel-btn ${filter === 'energy' ? 'active' : ''}`}
            onClick={() => setFilter('energy')}
          >
            Energy Surges
          </button>
        </div>
      </div>

      {/* Alert List */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
        {filteredAlerts.length === 0 ? (
          <div
            className="dashboard-panel"
            style={{ textAlign: 'center', padding: '48px 24px', color: 'var(--text-muted)' }}
          >
            <ShieldCheck size={48} color="var(--accent-emerald)" style={{ margin: '0 auto 12px auto' }} />
            <h3 style={{ color: 'var(--text-primary)', fontSize: 18 }}>All Systems Operating at Learned Baseline</h3>
            <p style={{ fontSize: 13, marginTop: 4 }}>No active edge anomaly flags recorded.</p>
          </div>
        ) : (
          filteredAlerts.map((alert) => {
            const isCritical = alert.severity === 'critical';

            return (
              <div
                key={alert.id}
                className="dashboard-panel"
                style={{
                  borderColor: alert.resolved
                    ? 'rgba(255,255,255,0.06)'
                    : isCritical
                    ? 'rgba(244, 63, 94, 0.4)'
                    : 'rgba(245, 158, 11, 0.4)',
                  opacity: alert.resolved ? 0.72 : 1,
                  transition: 'all 0.35s ease',
                }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                  <div style={{ display: 'flex', gap: 14 }}>
                    <div
                      style={{
                        padding: 10,
                        borderRadius: 'var(--radius-md)',
                        background: alert.resolved
                          ? 'rgba(255,255,255,0.05)'
                          : isCritical
                          ? 'rgba(244, 63, 94, 0.15)'
                          : 'rgba(245, 158, 11, 0.15)',
                        color: alert.resolved
                          ? 'var(--text-muted)'
                          : isCritical
                          ? 'var(--accent-rose)'
                          : 'var(--accent-amber)',
                        height: 'fit-content',
                      }}
                    >
                      {getCategoryIcon(alert.category)}
                    </div>

                    <div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' }}>
                        <h3 style={{ fontSize: 16, fontWeight: 700, color: '#fff' }}>{alert.title}</h3>
                        <span
                          style={{
                            fontSize: 10,
                            fontFamily: 'var(--font-mono)',
                            padding: '2px 8px',
                            borderRadius: 'var(--radius-pill)',
                            background: alert.resolved
                              ? 'rgba(16, 185, 129, 0.2)'
                              : isCritical
                              ? 'rgba(244, 63, 94, 0.2)'
                              : 'rgba(245, 158, 11, 0.2)',
                            color: alert.resolved
                              ? 'var(--accent-emerald)'
                              : isCritical
                              ? 'var(--accent-rose)'
                              : 'var(--accent-amber)',
                            fontWeight: 700,
                            textTransform: 'uppercase',
                          }}
                        >
                          {alert.resolved ? 'Resolved' : alert.severity}
                        </span>
                        {/* LIVE sync badge — visible to users when alert is resolved */}
                        {alert.resolved && (
                          <span className="live-resolved-badge">
                            <span className="live-dot" />
                            LIVE · Fixed by Owner
                          </span>
                        )}
                        <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>{alert.timestamp}</span>
                      </div>

                      <p style={{ color: 'var(--text-secondary)', fontSize: 13, marginTop: 6 }}>
                        {alert.description}
                      </p>

                      {/* Diagnostic details grid */}
                      <div
                        style={{
                          display: 'grid',
                          gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
                          gap: 12,
                          marginTop: 14,
                          padding: 12,
                          borderRadius: 'var(--radius-sm)',
                          background: 'rgba(0,0,0,0.25)',
                          fontSize: 12,
                        }}
                      >
                        <div>
                          <span style={{ color: 'var(--text-muted)' }}>Location:</span>{' '}
                          <strong>{alert.location}</strong>
                        </div>
                        <div>
                          <span style={{ color: 'var(--text-muted)' }}>Root Cause:</span>{' '}
                          <span style={{ color: '#fff' }}>{alert.rootCause}</span>
                        </div>
                        <div>
                          <span style={{ color: 'var(--text-muted)' }}>Potential Waste Prevented:</span>{' '}
                          <strong style={{ color: 'var(--accent-emerald)' }}>{alert.potentialSavings}</strong>
                        </div>
                        {!isUser && (
                          <div>
                            <span style={{ color: 'var(--text-muted)' }}>Recommended Action:</span>{' '}
                            <span style={{ color: '#fff' }}>{alert.recommendedAction}</span>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>

                  {/* Action Buttons */}
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 8, minWidth: 140 }}>
                    {/* Simulate in Twin — owner/admin only */}
                    {canSimulate && !alert.resolved && (
                      <button
                        id={`btn-sim-twin-${alert.id}`}
                        className="btn-primary"
                        style={{ fontSize: 12, padding: '7px 12px' }}
                        onClick={() => handleSimulateInTwin(alert.floor)}
                      >
                        <Layers size={13} />
                        Simulate in Twin
                      </button>
                    )}
                    {/* Mark Resolved — owner/admin only */}
                    {canResolve && !alert.resolved && (
                      <button
                        id={`btn-resolve-${alert.id}`}
                        className="btn-secondary"
                        style={{ fontSize: 12, padding: '7px 12px' }}
                        onClick={() => onResolveAlert(alert.id)}
                      >
                        <CheckCircle2 size={13} />
                        Mark Resolved
                      </button>
                    )}
                    {/* User view — read-only notice for unresolved alerts */}
                    {isUser && !alert.resolved && (
                      <div
                        style={{
                          fontSize: 11,
                          color: 'var(--text-muted)',
                          textAlign: 'center',
                          padding: '6px 10px',
                          border: '1px dashed rgba(255,255,255,0.1)',
                          borderRadius: 'var(--radius-sm)',
                          display: 'flex',
                          alignItems: 'center',
                          gap: 5,
                        }}
                      >
                        <Eye size={11} />
                        Awaiting owner action
                      </div>
                    )}
                  </div>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};
